language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=docs
  - TOX_ENV=pep8
matrix:
  allow_failures:
    - python: TOX_ENV=py33
before_install:
  - sudo apt-get install python-aeidon
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email:
    on_failure: always
    on_success: change
